spring.profiles.active: embeddedRedis

streams-master:
  center:
    name: PAC1
    type: sentinel1
    address: 131.30
    destination: /data/
    options:
      username: user
      password: pass

spring.redis.port: 6379
